driver:
  name: terraform
  root_module_directory: test/fixtures
  command_timeout: 1000

provisioner:
  name: terraform

verifier:
  name: terraform
  groups:
  - name: default

platforms:
  - name: terraform

suites:
  - name: default